# Generated by Django 5.0.1 on 2024-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='addres',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='order',
            name='plak',
            field=models.CharField(max_length=200, null=True, verbose_name='پلاک'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(max_length=200, null=True, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, verbose_name='شهر'),
        ),
    ]
