# Generated by Django 5.0.1 on 2024-02-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_addres_order_address_order_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
