# Generated by Django 5.0.1 on 2024-02-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=100, null=True, verbose_name='شماره پیگری سفارش'),
        ),
    ]
