# Generated by Django 5.0.1 on 2024-02-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_otp_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
