# Generated by Django 5.0.1 on 2024-02-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='titile',
            new_name='title',
        ),
    ]
