# Generated by Django 5.0.1 on 2024-02-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_titile_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='فروش'),
        ),
    ]
