# Generated by Django 5.0.1 on 2024-02-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerycategory',
            name='image',
            field=models.ImageField(null=True, upload_to='categories/', verbose_name='تصویر'),
        ),
    ]
