# Generated by Django 5.0.1 on 2024-02-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'راه ارتباطی', 'verbose_name_plural': 'راه های ارتباطی'},
        ),
        migrations.AlterModelOptions(
            name='usercontact',
            options={'verbose_name': 'پیام کاربر', 'verbose_name_plural': 'پیام های کاربر'},
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='title',
        ),
    ]
