# Generated by Django 5.0.1 on 2024-02-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_contact_options_alter_usercontact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram_id',
        ),
    ]
